/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import bdd.Connecter;
import java.sql.Connection;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modele.Entreprise;

/**
 *
 * @author Bilal
 */
public class ModifierEntreprise extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pr = null;
    ResultSet rs = null;
    Statement st = null;

    /**
     * Creates new form CreerEntreprise
     */
    public ModifierEntreprise() {
        con = Connecter.Connecter();
        
        initComponents();
        lesEntreprises();
    
    }
    // fonction affiche les offres
     public void montrerOffres() {
         String entreprise =ComboListeEntreprise.getSelectedItem().toString();
         String sql ="SELECT adresse_rue_entreprise,adresse_code_postal_entreprise,"
                         + "adresse_ville_entreprise,email_entreprise,tel_entreprise,secteur_activite"
                         + "FROM entreprise where nom_entreprise ="+entreprise;
        try {
            pr = con.prepareStatement(sql);
            rs = pr.executeQuery();
            while(rs.next()){
                          txtNumeroRue.setText(rs.getString("adresse_rue_entreprise"));
                          txtCodePostal.setText(rs.getString("adresse_code_postal_entreprise"));
                          txtVille.setText(rs.getString("adresse_ville_entreprise"));
                          txtMailContact.setText(rs.getString("email_entreprise"));
                          txtTelContact.setText(rs.getString("tel_entreprise"));
                          txtSecteur.setText(rs.getString("secteur_activite"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(ModifierEntreprise.class.getName()).log(Level.SEVERE, null, ex);
        }
           

    }
       // stocker les offre dans une liste des entreprises
    public List<Entreprise> lesEntreprises() {

        try {

            String sql = "select * FROM entreprise";
            pr = con.prepareStatement(sql);
            rs = pr.executeQuery();
            List<Entreprise> lesEntreprises = new ArrayList<Entreprise>();
            Entreprise e;
            while (rs.next()) {

                e = new Entreprise(
                        
                        rs.getString("nom_entreprise"),
                        rs.getString("adresse_ville_entreprise"),
                        rs.getString("adresse_rue_entreprise"),
                        rs.getString("adresse_code_postal_entreprise"),
                        rs.getString("tel_entreprise"),
                        rs.getString("email_entreprise"),
                        rs.getString("secteur_activite"));

                lesEntreprises.add(e);

                String nom = rs.getString("nom_entreprise");

                // nom de la combo
                ComboListeEntreprise.addItem(nom);

            }
            return lesEntreprises;

        } catch (Exception e) {
            return null;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNumeroRue = new javax.swing.JTextField();
        txtCodePostal = new javax.swing.JTextField();
        txtMailContact = new javax.swing.JTextField();
        txtTelContact = new javax.swing.JTextField();
        txtVille = new javax.swing.JTextField();
        txtSecteur = new javax.swing.JTextField();
        boutonSupprimerEntreprise = new javax.swing.JButton();
        boutonAnnulerEntreprise = new javax.swing.JButton();
        boutonMaj = new javax.swing.JButton();
        ComboListeEntreprise = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Copperplate", 1, 24)); // NOI18N
        jLabel1.setText("MODIFIER UNE ENTREPRISE");

        jLabel3.setText("Adresse (Numéro et rue)");

        jLabel4.setText("Adresse (Code Postal)");

        jLabel5.setText("Adresse (Ville)");

        jLabel6.setText("Mail du contact");

        jLabel7.setText("Secteur d'activité de l'entreprise");

        jLabel8.setText("Téléphone du contact");

        txtCodePostal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodePostalActionPerformed(evt);
            }
        });

        boutonSupprimerEntreprise.setText("Supprimer");
        boutonSupprimerEntreprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonSupprimerEntrepriseActionPerformed(evt);
            }
        });

        boutonAnnulerEntreprise.setText("Annuler");
        boutonAnnulerEntreprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAnnulerEntrepriseActionPerformed(evt);
            }
        });

        boutonMaj.setText("Mettre à jour");
        boutonMaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonMajActionPerformed(evt);
            }
        });

        ComboListeEntreprise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComboListeEntrepriseMouseClicked(evt);
            }
        });

        jLabel9.setText("Choix de l'entreprise à modifier :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtSecteur, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelContact, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMailContact, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVille, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodePostal, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNumeroRue, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(boutonMaj)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(boutonSupprimerEntreprise)
                                        .addGap(132, 132, 132)))
                                .addComponent(boutonAnnulerEntreprise))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(96, 96, 96)
                                .addComponent(ComboListeEntreprise, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(57, 57, 57))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboListeEntreprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroRue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCodePostal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMailContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSecteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boutonSupprimerEntreprise)
                    .addComponent(boutonMaj)
                    .addComponent(boutonAnnulerEntreprise))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boutonSupprimerEntrepriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonSupprimerEntrepriseActionPerformed

        try {
            String nom = ComboListeEntreprise.getSelectedItem().toString();
            String sql = "delete from entreprise  where nom_entreprise ='" + nom+"'";
            st = con.createStatement();
            st.executeUpdate(sql);

            JOptionPane.showMessageDialog(null, "l'offre est supprimée");
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "erreur :" + e);

        }

    }//GEN-LAST:event_boutonSupprimerEntrepriseActionPerformed

    private void txtCodePostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodePostalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodePostalActionPerformed

    private void boutonAnnulerEntrepriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAnnulerEntrepriseActionPerformed
        this.setVisible(false);
        new GestionDesOffres().setVisible(true);
    }//GEN-LAST:event_boutonAnnulerEntrepriseActionPerformed

    private void boutonMajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonMajActionPerformed
        if(txtVille.getText().equals("")||
                    txtNumeroRue.getText().equals("")||
                    txtCodePostal.getText().equals("")||
                    txtTelContact.getText().equals("")||
                     txtMailContact.getText().equals("")||
                     txtSecteur.getText().equals("")){
            // verification des champs
            JOptionPane.showMessageDialog(null, "verifiez les champs !!!");
        }else{
        try {
            String nom = ComboListeEntreprise.getSelectedItem().toString();
            String sql = "update entreprise set "
                    + "adresse_ville_entreprise = '" + txtVille.getText()
                    + "',adresse_rue_entreprise = '" + txtNumeroRue.getText()
                    + "',adresse_code_postal_entreprise= '" + txtCodePostal.getText()
                    + "', tel_entreprise	 = '" + txtTelContact.getText()
                    + "',email_entreprise = '" + txtMailContact.getText()
                    + "' ,secteur_activite= '" + txtSecteur.getText() + "'  where nom_entreprise ='" + nom+"'";//bloqué toute la journée à cause des côtes du nom

            st = con.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "mise à jour ok");
            this.setVisible(false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur : " + e);
        }
                        }
    }//GEN-LAST:event_boutonMajActionPerformed

    private void ComboListeEntrepriseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboListeEntrepriseMouseClicked
       montrerOffres();
    }//GEN-LAST:event_ComboListeEntrepriseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifierEntreprise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifierEntreprise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifierEntreprise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifierEntreprise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifierEntreprise().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboListeEntreprise;
    private javax.swing.JButton boutonAnnulerEntreprise;
    private javax.swing.JButton boutonMaj;
    private javax.swing.JButton boutonSupprimerEntreprise;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCodePostal;
    private javax.swing.JTextField txtMailContact;
    private javax.swing.JTextField txtNumeroRue;
    private javax.swing.JTextField txtSecteur;
    private javax.swing.JTextField txtTelContact;
    private javax.swing.JTextField txtVille;
    // End of variables declaration//GEN-END:variables
}
